#!/usr/bin/env bash
# Generates a .env file with random bearer tokens.
# Usage: bash scripts/generate_config.sh
set -euo pipefail

TARGET=.env

if [ -f "$TARGET" ]; then
  echo "ERROR: $TARGET already exists. Remove it first or edit it manually." >&2
  exit 1
fi

rand() { openssl rand -hex 32; }

cat > "$TARGET" <<EOF
# Auto-generated by scripts/generate_config.sh — edit as needed.

ADMIN_TOKEN=$(rand)
DATASETTE_TOKEN=$(rand)
EXPORT_TOKEN=$(rand)
MCP_TOKEN=$(rand)

APP_BASE_URL=http://localhost:8080
HOME_TZ=America/New_York
DB_PATH=/data/health.db

# Garmin — uncomment one method:
#GARMINTOKENS=
#GARMIN_EMAIL=
#GARMIN_PASSWORD=

# Google Health OAuth — see README for setup steps:
#GOOGLE_CLIENT_ID=
#GOOGLE_CLIENT_SECRET=

# Litestream backup (optional):
#LITESTREAM_REPLICA_URL=
EOF

echo "Created $TARGET with random tokens."
echo "Edit it to add Garmin credentials and other optional settings."
