#!/usr/bin/env bash
# Generates a .env file with random bearer tokens and optionally fetches Garmin session tokens.
# Usage: bash scripts/generate_config.sh
set -euo pipefail

TARGET=.env

if [ -f "$TARGET" ]; then
  echo "ERROR: $TARGET already exists. Remove it first or edit it manually." >&2
  exit 1
fi

rand() { openssl rand -hex 32; }

# Write base config with generated tokens
cat > "$TARGET" <<EOF
# Auto-generated by scripts/generate_config.sh — edit as needed.

ADMIN_TOKEN=$(rand)
DATASETTE_TOKEN=$(rand)
EXPORT_TOKEN=$(rand)
MCP_TOKEN=$(rand)

APP_BASE_URL=http://localhost:8080
HOME_TZ=America/New_York
DB_PATH=/data/health.db

# Garmin — filled in below if you completed setup, otherwise uncomment one method manually:
#GARMINTOKENS=
#GARMIN_EMAIL=
#GARMIN_PASSWORD=

# Google Health OAuth — see README for setup steps:
#GOOGLE_CLIENT_ID=
#GOOGLE_CLIENT_SECRET=

# Litestream backup (optional):
#LITESTREAM_REPLICA_URL=

# Morning webhook — URL and secret come from your Claude Routine trigger (optional):
#MORNING_WEBHOOK_URL=
#MORNING_WEBHOOK_SECRET=
EOF

echo "Created $TARGET with random tokens."
echo ""

# Optional Garmin auth
read -r -p "Set up Garmin auth now? (y/N) " garmin_answer
if [[ "${garmin_answer,,}" != "y" ]]; then
  echo "Skipping Garmin setup. Edit $TARGET manually when ready."
  exit 0
fi

read -r -p "Garmin email: " garmin_email
read -r -s -p "Garmin password: " garmin_password
echo ""

echo "Fetching Garmin session tokens..."

# Try local Python first, fall back to Docker
GARMIN_SCRIPT='
import sys
try:
    from garminconnect import Garmin
except ImportError:
    sys.exit(2)
import json, os
g = Garmin(os.environ["GARMIN_EMAIL"], os.environ["GARMIN_PASSWORD"])
g.login()
print(g.garth.dumps())
'

garmin_tokens=""
if GARMIN_TOKENS_OUT=$(GARMIN_EMAIL="$garmin_email" GARMIN_PASSWORD="$garmin_password" \
    python3 -c "$GARMIN_SCRIPT" 2>/dev/null); then
  garmin_tokens="$GARMIN_TOKENS_OUT"
elif docker info &>/dev/null; then
  echo "(garminconnect not found locally — trying via Docker build...)"
  garmin_tokens=$(docker run --rm \
    -e GARMIN_EMAIL="$garmin_email" \
    -e GARMIN_PASSWORD="$garmin_password" \
    "$(docker build -q .)" \
    python3 -c "$GARMIN_SCRIPT" 2>/dev/null) || true
fi

if [ -n "$garmin_tokens" ]; then
  # Replace the commented-out GARMINTOKENS placeholder
  # Use a temp file to avoid sed -i portability issues
  tmp=$(mktemp)
  grep -v '^#GARMINTOKENS=' "$TARGET" > "$tmp"
  echo "GARMINTOKENS=$(printf '%s' "$garmin_tokens")" >> "$tmp"
  mv "$tmp" "$TARGET"
  echo "Garmin tokens written to $TARGET."
else
  echo "Could not fetch Garmin tokens automatically."
  echo "After starting the app, get them manually:"
  echo "  python3 -c \"from garminconnect import Garmin; g=Garmin(); g.login('$garmin_email', '...'); print(g.garth.dumps())\""
  echo "Then set GARMINTOKENS in $TARGET."
fi

echo ""

# Optional Google Health auth
read -r -p "Set up Google Health now? (y/N) " gh_answer
if [[ "${gh_answer,,}" != "y" ]]; then
  echo "Skipping Google Health setup. See README for manual instructions."
  exit 0
fi

echo "You'll need an OAuth 2.0 Client ID from Google Cloud Console."
echo "  1. Go to console.cloud.google.com → APIs & Services → Credentials"
echo "  2. Create an OAuth 2.0 Client ID (type: Web application)"
echo "  3. Add authorized redirect URI: \${APP_BASE_URL}/google_health_callback"
echo ""
read -r -p "Google OAuth Client ID: " gh_client_id
read -r -p "Google OAuth Client Secret: " gh_client_secret
echo ""

tmp=$(mktemp)
grep -v '^#GOOGLE_CLIENT_ID=' "$TARGET" | grep -v '^#GOOGLE_CLIENT_SECRET=' > "$tmp"
echo "GOOGLE_CLIENT_ID=$gh_client_id" >> "$tmp"
echo "GOOGLE_CLIENT_SECRET=$gh_client_secret" >> "$tmp"
mv "$tmp" "$TARGET"

echo "Google Health credentials written to $TARGET."
echo ""
echo "After starting the app ('docker compose up -d'), complete the OAuth flow:"
echo "  python3 scripts/google_health_get_tokens.py --base-url http://localhost:8080 --token \$ADMIN_TOKEN"
